var qsetmeta = {
  metadata: {
    max_score: 1,
    isShuffleOption: false,
    isPartialScore: true,
    evalUnordered: false,
    templateType: 'Horizontal',
    name: 'How are you ?\n',
    title: 'How are you ?\n',
    board: 'CBSE',
    medium: 'Assamese',
    gradeLevel: ['KG'],
    subject: 'Accountancy',
    qlevel: 'EASY',
    category: 'MCQ',
  },
  max_time: 0,
  max_score: 1,
  partial_scoring: true,
  layout: 'Horizontal',
  isShuffleOption: false,
  questionCount: 1,
  evalUnordered: false,
}
